name: Dep

# Lancement depuis gitHub action

on:
  workflow_dispatch:

concurrency:
  group: production-deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy front + back sans Docker
    runs-on: ubuntu-latest

# Connexion SSH au serveur 
    steps:
      - name: Deployer via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            set -e
            #  Maj le code
            cd /opt/metr
            git pull origin main

            # Installer et maj le backend
            cd /opt/metr/back_end_M-R
            npm ci --omit=dev

            # Redemarrer le back avec PM2
            pm2 describe metr-backend > /dev/null 2>&1 && pm2 restart metr-backend || pm2 start server.js --name metr-backend
            pm2 save

            # Build le front
            cd /opt/metr/marche-et-ramasse
            npm ci
            npm run build

            #Envoyer le front Nginx
            sudo rm -rf /var/www/metr/*
            sudo cp -r dist/* /var/www/metr/

            #  Recharger Nginx
            sudo nginx -t
            sudo systemctl reload nginx

            echo "Deploiement termine "
